### ISSUE TITLE
Get rid of %

### ISSUE THREAD

**Issue by evshvarov** [rcemper/Terminal-Multi-Line-Option#1]
Better rcemper.multiline.cls
or dc.multiline.cls

**Comment by rcemper** [comment]
not clear how this is then namespace independent without touching Routine & Package mapping for %ALL
- % instead of %ALL mapping which is mostly not understood,
-  Z not to be erased by the next upgrade

**Comment by evshvarov** [comment]
Why would you need it namespace independent?
But, OK - if you think this is mandatory.
